name: config of answer generation for arena-hard-v0.1

bench_name: arena-hard-v0.1

temperature: 0.0
max_tokens: 2048
num_choices: 1

# a list of model to generate answers
model_list:
  - think_hybrid_llama_8b_merged_reasoning_1074k_generall_nothink_oasst2_1749k_40995_prompt_llama_think_t0.6_mt35000_seed1234
